// DO NOT EDIT
// This file is autogenerated
// use `pnpm codegen` to update
// If you want to make changes, edit the file scripts/generate-types.ts

// exporting scalars
export * from './scalars/Decimal'

// exporting inputs
export * from './inputs/FilterInputs'

// exporting objects
export * from './objects/Institution'
export * from './objects/InstitutionEstrategicObjetive'
export * from './objects/InstitutionalPlan'
export * from './objects/Person'
export * from './objects/Program'
export * from './objects/Project'
export * from './objects/ProjectGoal'
export * from './objects/User'

// exporting queries
export * from './queries/institution/list'
export * from './queries/institution/one'
export * from './queries/institution/root'
export * from './queries/institutionalPlan/list'
export * from './queries/institutionalPlan/one'
export * from './queries/institutionalPlan/root'
export * from './queries/program/list'
export * from './queries/program/one'
export * from './queries/program/root'
export * from './queries/project/list'
export * from './queries/project/one'
export * from './queries/project/root'
export * from './queries/projectGoal/list'
export * from './queries/projectGoal/one'
export * from './queries/projectGoal/root'
export * from './queries/user/list'
export * from './queries/user/one'
export * from './queries/user/root'

// exporting mutations
export * from './mutations/institution/create'
export * from './mutations/institution/root'
export * from './mutations/institution/update'
export * from './mutations/institutionalPlan/create'
export * from './mutations/institutionalPlan/root'
export * from './mutations/institutionalPlan/update'
export * from './mutations/program/create'
export * from './mutations/program/root'
export * from './mutations/program/update'
export * from './mutations/project/create'
export * from './mutations/project/root'
export * from './mutations/project/update'
export * from './mutations/projectGoal/create'
export * from './mutations/projectGoal/root'
export * from './mutations/projectGoal/update'
export * from './mutations/user/create'
export * from './mutations/user/root'
export * from './mutations/user/update'

// exporting enums
export * from './enums/InstitutionArea'
export * from './enums/InstitutionLevel'
export * from './enums/ProjectGoalStatus'
export * from './enums/ProjectStatus'
