// DO NOT EDIT
// This file is autogenerated
// use `pnpm generate` to update
// If you want to make changes, edit the file scripts/generate.ts

// exporting tables
export * from './tables/alignmentObjectiveEstrategicWithPND'
export * from './tables/alignmentObjectivePNDWithODS'
export * from './tables/institution'
export * from './tables/institutionalClassification'
export * from './tables/institutionalEstrategicObjetive'
export * from './tables/institutionalPlan'
export * from './tables/institutionalUnit'
export * from './tables/objectiveODS'
export * from './tables/objectivePND'
export * from './tables/permissionRole'
export * from './tables/person'
export * from './tables/program'
export * from './tables/project'
export * from './tables/projectTask'
export * from './tables/role'
export * from './tables/user'
export * from './tables/userRole'
